### PR TITLE
check python exists when python_executable is present

### PR DESCRIPTION
**Pull request by amatsuo**
Addresses #49

### CODE REVIEW

**Comment by kbenoit** [comment]
@amatsuo can you get the test to pass when you uncomment the code in `tests/testthat/test-spacy_initialize.R`? It works in the console for me but not in the test, for some reason.

**Comment by amatsuo** [comment]
@kbenoit I believe the problem is solved. The issue was the order of test (which obviously the order of file names).  This `spacy_initialize` test has to be executed before other tests.

If the `tests/testthat/test-spacy_initialize.R` is executed after other tests, the reticulate python is already set, and therefore, the `python_executable` argument is ignored. This is an intended behavior of the function because once `reticulate` python is initialized, there is no way to switch python and so there is no point to check it.

**Comment by kbenoit** [comment]
How did you change the order?

**Comment by amatsuo** [comment]
rename the test file names (e.g. `test-1-spacy-initialize.R`)

**Pull request merged**
